const PETS = [
    {
        id: 1,
        name: "Huge Starlight Hamster",
        rarity: "Huge",
        value: "62.5M",
        demand: "10/10",
        demandLevel: 5,
        trend: "Rising",
        exists: "9",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeStarlightHamster.png"
    },
    {
        id: 2,
        name: "Huge Mining Kraken",
        rarity: "Huge",
        value: "5.25M",
        demand: "6.5/10",
        demandLevel: 3,
        trend: "Stable",
        exists: "9",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeMiningKraken.png"
    },
    {
        id: 3,
        name: "Huge Shadow Sphinx",
        rarity: "Huge",
        value: "1.15M",
        demand: "4/10",
        demandLevel: 2,
        trend: "Falling",
        exists: "27",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeShadowSphinx.png"
    },
    {
        id: 4,
        name: "Huge Empyrean Scorpion",
        rarity: "Huge",
        value: "40.5M",
        demand: "8/10",
        demandLevel: 4,
        trend: "Rising",
        exists: "3",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeEmpyreanScorpion.png"
    },
    {
        id: 5,
        name: "Huge Hellish Dominus",
        rarity: "Huge",
        value: "20.5M",
        demand: "8/10",
        demandLevel: 4,
        trend: "Rising",
        exists: "4",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeHellishDominus.png"
    },
    {
        id: 6,
        name: "Huge Easter Mimic Chest",
        rarity: "Huge",
        value: "2M",
        demand: "5/10",
        demandLevel: 2,
        trend: "Stable",
        exists: "16",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeEasterChest.png"
    },
    {
        id: 7,
        name: "Huge Painted Bunny",
        rarity: "Huge",
        value: "10.5M",
        demand: "7/10",
        demandLevel: 3,
        trend: "Stable",
        exists: "5",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugePaintedBunny.png"
    },
    {
        id: 8,
        name: "Huge Sensei Cat",
        rarity: "Huge",
        value: "8.5M",
        demand: "6/10",
        demandLevel: 3,
        trend: "Stable",
        exists: "8",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeSenseiCat_Basic.png"
    },
    {
        id: 9,
        name: "Huge Kaiju Bearserker",
        rarity: "Huge",
        value: "5.5M",
        demand: "5/10",
        demandLevel: 2,
        trend: "Stable",
        exists: "10",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeKaijuBerserker_Basic.png"
    },
    {
        id: 10,
        name: "Huge Broken Mining Robot",
        rarity: "Huge",
        value: "17.5M",
        demand: "7/10",
        demandLevel: 3,
        trend: "Stable",
        exists: "7",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeBrokenMiningRobot.png"
    },
    {
        id: 11,
        name: "Huge Abyss Agony",
        rarity: "Huge",
        value: "750K",
        demand: "7/10",
        demandLevel: 3.5,
        trend: "Falling",
        exists: "108",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeAbyssAgony.png"
    },
    {
        id: 12,
        name: "Huge Onyx Gem Golem",
        rarity: "Huge",
        value: "15M",
        demand: "9/10",
        demandLevel: 4.5,
        trend: "Rising",
        exists: "5",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeOnyxGolem.png"
    },
    {
        id: 13,
        name: "Huge Nyan Dog",
        rarity: "Huge",
        value: "12.5M",
        demand: "7.5/10",
        demandLevel: 3.75,
        trend: "Stable",
        exists: "5",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeNyanDog.png"
    },
    {
        id: 14,
        name: "Huge Gift Mining Cat",
        rarity: "Huge",
        value: "3M",
        demand: "6.5/10",
        demandLevel: 3,
        trend: "Stable",
        exists: "14",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeGiftMiningCat.png"
    },
    {
        id: 15,
        name: "Huge Dominus Minecart Astra",
        rarity: "Huge",
        value: "6.75M",
        demand: "7/10",
        demandLevel: 3.5,
        trend: "Stable",
        exists: "10",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/huge1.png"
    },
    {
        id: 16,
        name: "Huge Release Penguin",
        rarity: "Huge",
        value: "6.5M",
        demand: "6.5/10",
        demandLevel: 3,
        trend: "Stable",
        exists: "10",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeReleasePenguin.png"
    },
    {
        id: 17,
        name: "Huge Basket Nightmare Cat",
        rarity: "Huge",
        value: "70m",
        demand: "10/10",
        demandLevel: 4.75,
        trend: "Rising",
        exists: "3",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeBasketNightmare.png"
    },
    {
        id: 18,
        name: "Huge Abstract Cat",
        rarity: "Huge",
        value: "1.85M",
        demand: "6.5/10",
        demandLevel: 3,
        trend: "Stable",
        exists: "19",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeAbstractCat.png"
    },
    {
        id: 19,
        name: "Secret Archgelus",
        rarity: "Secret",
        value: "300K",
        demand: "7/10",
        demandLevel: 3.5,
        trend: "Stable",
        exists: "14",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/archgelus.png"
    },
    {
        id: 20,
        name: "Secret Camo Rave Tiki Cat",
        rarity: "Secret",
        value: "O/C",
        demand: "Nil",
        demandLevel: 0,
        trend: "Rising",
        exists: "2",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/camo.png"
    },
    {
        id: 21,
        name: "Secret Release Lucki",
        rarity: "Secret",
        value: "225K",
        demand: "7/10",
        demandLevel: 3.5,
        trend: "Stable",
        exists: "15",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/releaselucki.png"
    },
    {
        id: 22,
        name: "Secret Gift Mining Cat",
        rarity: "Secret",
        value: "15K",
        demand: "0/10",
        demandLevel: 0,
        trend: "Falling",
        exists: "167",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/miningcat.png"
    },
    {
        id: 23,
        name: "Blossom Spirit Cat",
        rarity: "Secret",
        value: "22.5K",
        demand: "2/10",
        demandLevel: 1,
        trend: "Falling",
        exists: "99",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/blossomspirit.png"
    },
    {
        id: 24,
        name: "Secret M-33 Prototype",
        rarity: "Secret",
        value: "450K",
        demand: "7/10",
        demandLevel: 3.5,
        trend: "Rising",
        exists: "8",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/prototype.png"
    },
    {
        id: 25,
        name: "Secret Cool Zen Fish",
        rarity: "Secret",
        value: "4.25M",
        demand: "8/10",
        demandLevel: 4,
        trend: "Stable",
        exists: "11",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/CoolZenFish2_Basic.png"
    },
    {
        id: 26,
        name: "Secret Release Trophy Dominus",
        rarity: "Secret",
        value: "O/C",
        demand: "Nil",
        demandLevel: 0,
        trend: "Stable",
        exists: "1",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/trophy.png"
    },
    {
        id: 27,
        name: "Secret Gift Bag Tiger",
        rarity: "Secret",
        value: "O/C",
        demand: "Nil",
        demandLevel: 0,
        trend: "Stable",
        exists: "0",
        image: ""
    },
    {
        id: 28,
        name: "Secret Shadow Firefly",
        rarity: "Secret",
        value: "10K",
        demand: "1/10",
        demandLevel: 0.5,
        trend: "Falling",
        exists: "172",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/shadowfirefly.png"
    },
    {
        id: 29,
        name: "Secret GIANT Sand Mantis Shrimp",
        rarity: "Secret",
        value: "O/C",
        demand: "Nil",
        demandLevel: 0,
        trend: "Stable",
        exists: "1",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/giantsandmantisshrimp.png"
    },
    {
        id: 30,
        name: "Secret Ice King Immortuss",
        rarity: "Secret",
        value: "125K",
        demand: "7.5/10",
        demandLevel: 3.75,
        trend: "Stable",
        exists: "5",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/icekingmortuus.png"
    },
    {
        id: 31,
        name: "Secret ROUND",
        rarity: "Secret",
        value: "O/C",
        demand: "Nil",
        demandLevel: 0,
        trend: "Stable",
        exists: "2",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/round.png"
    },
    {
        id: 32,
        name: "Secret Snowflake Dog",
        rarity: "Secret",
        value: "325k",
        demand: "8/10",
        demandLevel: 4,
        trend: "Rising",
        exists: "12",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/Snowflakedog.png"
    }
];