window.PETS = [
    {
        id: 1,
        name: "Huge Starlight Hamster",
        rarity: "Huge",
        value: "69M",
        demand: "10/10",
        demandLevel: 5,
        trend: "Rising",
        exists: "9",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeStarlightHamster.png"
    },
    {
        id: 2,
        name: "Huge Mining Kraken",
        rarity: "Huge",
        value: "8.5M",
        demand: "8/10",
        demandLevel: 3,
        trend: "Rising",
        exists: "9",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeMiningKraken.png"
    },
    {
        id: 3,
        name: "Huge Shadow Sphinx",
        rarity: "Huge",
        value: "750K",
        demand: "4/10",
        demandLevel: 2,
        trend: "Falling",
        exists: "46",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeShadowSphinx.png"
    },
    {
        id: 4,
        name: "Huge Empyrean Scorpion",
        rarity: "Huge",
        value: "19M",
        demand: "8/10",
        demandLevel: 4,
        trend: "Falling",
        exists: "6",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeEmpyreanScorpion.png"
    },
    {
        id: 5,
        name: "Huge Hellish Dominus",
        rarity: "Huge",
        value: "15M",
        demand: "8/10",
        demandLevel: 4,
        trend: "Falling",
        exists: "10",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeHellishDominus.png"
    },
    {
        id: 6,
        name: "Huge Easter Mimic Chest",
        rarity: "Huge",
        value: "6M",
        demand: "5/10",
        demandLevel: 2,
        trend: "Rising",
        exists: "16",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeEasterChest.png"
    },
    {
        id: 7,
        name: "Huge Painted Bunny",
        rarity: "Huge",
        value: "13.5M",
        demand: "7/10",
        demandLevel: 3,
        trend: "Rising",
        exists: "5",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugePaintedBunny.png"
    },
    {
        id: 8,
        name: "Huge Sensei Cat",
        rarity: "Huge",
        value: "15.5M",
        demand: "6/10",
        demandLevel: 3,
        trend: "Rising",
        exists: "8",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeSenseiCat_Basic.png"
    },
    {
        id: 9,
        name: "Huge Kaiju Bearserker",
        rarity: "Huge",
        value: "10M",
        demand: "5/10",
        demandLevel: 2,
        trend: "Rising",
        exists: "10",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeKaijuBerserker_Basic.png"
    },
    {
        id: 10,
        name: "Huge Broken Mining Robot",
        rarity: "Huge",
        value: "21.5M",
        demand: "7/10",
        demandLevel: 3,
        trend: "Rising",
        exists: "6",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeBrokenMiningRobot.png"
    },
    {
        id: 11,
        name: "Huge Abyss Agony",
        rarity: "Huge",
        value: "765K",
        demand: "7/10",
        demandLevel: 3.5,
        trend: "Rising",
        exists: "108",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeAbyssAgony.png"
    },
    {
        id: 12,
        name: "Huge Onyx Gem Golem",
        rarity: "Huge",
        value: "66M",
        demand: "9/10",
        demandLevel: 4.5,
        trend: "Rising",
        exists: "5",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeOnyxGolem.png"
    },
    {
        id: 13,
        name: "Huge Nyan Dog",
        rarity: "Huge",
        value: "6.5M",
        demand: "7.5/10",
        demandLevel: 3.75,
        trend: "Rising",
        exists: "18",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeNyanDog.png"
    },
    {
        id: 14,
        name: "Huge Gift Mining Cat",
        rarity: "Huge",
        value: "8M",
        demand: "6.5/10",
        demandLevel: 3,
        trend: "Rising",
        exists: "14",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeGiftMiningCat.png"
    },
    {
        id: 15,
        name: "Huge Dominus Minecart Astra",
        rarity: "Huge",
        value: "O/C",
        demand: "10/10",
        demandLevel: 3.5,
        trend: "Stable",
        exists: "10",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/huge1.png"
    },
    {
        id: 16,
        name: "Huge Release Penguin",
        rarity: "Huge",
        value: "7M",
        demand: "6.5/10",
        demandLevel: 3,
        trend: "Rising",
        exists: "11",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeReleasePenguin.png"
    },
    {
        id: 17,
        name: "Huge Basket Nightmare Cat",
        rarity: "Huge",
        value: "115M",
        demand: "10/10",
        demandLevel: 4.75,
        trend: "Rising",
        exists: "7",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeBasketNightmare.png"
    },
    {
        id: 18,
        name: "Huge Abstract Cat",
        rarity: "Huge",
        value: "3M",
        demand: "6.5/10",
        demandLevel: 3,
        trend: "Rising",
        exists: "25",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/HugeAbstractCat.png"
    },
    {
        id: 19,
        name: "Secret Archgelus",
        rarity: "Secret",
        value: "300K",
        demand: "7/10",
        demandLevel: 3.5,
        trend: "Stable",
        exists: "14",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/archgelus.png"
    },
    {
        id: 20,
        name: "Secret Camo Rave Tiki Cat",
        rarity: "Secret",
        value: "O/C",
        demand: "Nil",
        demandLevel: 0,
        trend: "Rising",
        exists: "2",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/camo.png"
    },
    {
        id: 21,
        name: "Secret Release Lucki",
        rarity: "Secret",
        value: "225K",
        demand: "7/10",
        demandLevel: 3.5,
        trend: "Stable",
        exists: "15",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/releaselucki.png"
    },
    {
        id: 22,
        name: "Secret Gift Mining Cat",
        rarity: "Secret",
        value: "15K",
        demand: "0/10",
        demandLevel: 0,
        trend: "Falling",
        exists: "167",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/miningcat.png"
    },
    {
        id: 23,
        name: "Blossom Spirit Cat",
        rarity: "Secret",
        value: "22.5K",
        demand: "2/10",
        demandLevel: 1,
        trend: "Falling",
        exists: "99",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/blossomspirit.png"
    },
    {
        id: 24,
        name: "Secret M-33 Prototype",
        rarity: "Secret",
        value: "450K",
        demand: "7/10",
        demandLevel: 3.5,
        trend: "Rising",
        exists: "8",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/prototype.png"
    },
    {
        id: 25,
        name: "Secret Cool Zen Fish",
        rarity: "Secret",
        value: "4.25M",
        demand: "8/10",
        demandLevel: 4,
        trend: "Stable",
        exists: "11",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/CoolZenFish2_Basic.png"
    },
    {
        id: 26,
        name: "Secret Release Trophy Dominus",
        rarity: "Secret",
        value: "O/C",
        demand: "Nil",
        demandLevel: 2,
        trend: "Stable",
        exists: "2",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/trophy.png"
    },
    {
        id: 27,
        name: "Secret Gift Bag Tiger",
        rarity: "Secret",
        value: "400K",
        demand: "8/10",
        demandLevel: 2,
        trend: "Stable",
        exists: "4",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/giftbagtiger.png"
    },
    {
        id: 28,
        name: "Secret Shadow Firefly",
        rarity: "Secret",
        value: "10K",
        demand: "1/10",
        demandLevel: 0.5,
        trend: "Falling",
        exists: "172",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/shadowfirefly.png"
    },
    {
        id: 29,
        name: "Secret GIANT Sand Mantis Shrimp",
        rarity: "Secret",
        value: "O/C",
        demand: "Nil",
        demandLevel: 0,
        trend: "Stable",
        exists: "1",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/giantsandmantisshrimp.png"
    },
    {
        id: 30,
        name: "Secret Ice King Immortuss",
        rarity: "Secret",
        value: "125K",
        demand: "7.5/10",
        demandLevel: 3.75,
        trend: "Stable",
        exists: "5",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/icekingmortuus.png"
    },
    {
        id: 31,
        name: "Secret ROUND",
        rarity: "Secret",
        value: "O/C",
        demand: "Nil",
        demandLevel: 0,
        trend: "Stable",
        exists: "2",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/round.png"
    },
    {
        id: 32,
        name: "Secret Snowflake Dog",
        rarity: "Secret",
        value: "325k",
        demand: "8/10",
        demandLevel: 4,
        trend: "Rising",
        exists: "12",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/Snowflakedog.png"
    },
    {
        id: 33,
        name: "Huge Obsidian Butterfly",
        rarity: "Huge",
        value: "6.5M",
        demand: "7/10",
        demandLevel: 3.5,
        trend: "Stable",
        exists: "15",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/obsidianbutterfly.png"
    },
    {
        id: 34,
        name: "Huge Raingelus",
        rarity: "Huge",
        value: "3.2M",
        demand: "6/10",
        demandLevel: 3,
        trend: "Stable",
        exists: "24",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/raingelus.png"
    },
    {
        id: 35,
        name: "Huge Blueberry Kitsune",
        rarity: "Huge",
        value: "7M",
        demand: "8/10",
        demandLevel: 4,
        trend: "Stable",
        exists: "???",
        image: ""
    },
    {
        id: 36,
        name: "Huge Doom Bunny",
        rarity: "Huge",
        value: "600K",
        demand: "5/10",
        demandLevel: 2.5,
        trend: "Stable",
        exists: "94",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/doombunny.png"
    },
    {
        id: 37,
        name: "Huge Celestial Wolf",
        rarity: "Huge",
        value: "1.3M",
        demand: "6/10",
        demandLevel: 3,
        trend: "Stable",
        exists: "60",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/celestialwolf.png"
    },
    {
        id: 38,
        name: "Huge Sun Fox",
        rarity: "Huge",
        value: "1.9M",
        demand: "6.5/10",
        demandLevel: 3.25,
        trend: "Stable",
        exists: "44",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/sunfox.png"
    },
    {
        id: 39,
        name: "Huge Terror Slime Mech Cat",
        rarity: "Huge",
        value: "1.75M",
        demand: "7/10",
        demandLevel: 3.5,
        trend: "Stable",
        exists: "50",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/terrorcat.png"
    },
    {
        id: 40,
        name: "Huge Abyss Dragon",
        rarity: "Huge",
        value: "17.5M",
        demand: "8/10",
        demandLevel: 4,
        trend: "Stable",
        exists: "12",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/abyssdragon.png"
    },
    {
        id: 41,
        name: "Huge Crystal Pegasus",
        rarity: "Huge",
        value: "50M",
        demand: "9/10",
        demandLevel: 4.5,
        trend: "Stable",
        exists: "4",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/crystalpegasus.png"
    },
    {
        id: 42,
        name: "Huge Gubert",
        rarity: "Huge",
        value: "40M",
        demand: "9/10",
        demandLevel: 4.5,
        trend: "Stable",
        exists: "6",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/gubertcat.png"
    },
    {
        id: 43,
        name: "Huge Plasma Axolotl",
        rarity: "Huge",
        value: "2.7M",
        demand: "7/10",
        demandLevel: 3.5,
        trend: "Rising",
        exists: "36",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/plasmaaxol.png"
    },
    {
        id: 44,
        name: "Huge Creepy Raccoon",
        rarity: "Huge",
        value: "1.85M",
        demand: "6/10",
        demandLevel: 3,
        trend: "Rising",
        exists: "48",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/creepyracoon.png"
    },
    {
        id: 45,
        name: "Huge Old Archangel Kangaroo",
        rarity: "Huge",
        value: "4.5M",
        demand: "8/10",
        demandLevel: 4,
        trend: "Rising",
        exists: "22",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/oldarch.png"
    },
    {
        id: 46,
        name: "Huge Tech Samurai Kitsune",
        rarity: "Huge",
        value: "5M",
        demand: "8/10",
        demandLevel: 4,
        trend: "Rising",
        exists: "19",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/techsamurai.png"
    },
    {
        id: 47,
        name: "Huge Pixel Archgelus",
        rarity: "Huge",
        value: "18M",
        demand: "9/10",
        demandLevel: 4.5,
        trend: "Rising",
        exists: "10",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/pixelarchgelus.png"
    },
    {
        id: 48,
        name: "Huge Super Coral Dragon",
        rarity: "Huge",
        value: "6M",
        demand: "7/10",
        demandLevel: 3.5,
        trend: "Rising",
        exists: "16",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/coraldragon.png"
    },
    {
        id: 49,
        name: "Huge Super Coral Dominus",
        rarity: "Huge",
        value: "O/C",
        demand: "Nil",
        demandLevel: 0,
        trend: "Stable",
        exists: "2",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/coraldominus.png"
    },
    {
        id: 50,
        name: "Huge Venom Corgi",
        rarity: "Huge",
        value: "7.5m",
        demand: "8/10",
        demandLevel: 0,
        trend: "Rising",
        exists: "???",
        image: "https://raw.githubusercontent.com/devxgamesontop-ctrl/PEINF/main/venomcorgi.png"
    }
];  

    
        